{% set name = "libdrm" %}
{% set version = "2.4.96" %}

# http://www.linuxfromscratch.org/blfs/view/8.2/x/libdrm.html

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://dri.freedesktop.org/libdrm/libdrm-{{ version }}.tar.gz
  sha256: d2bba5ca2ddfbdbc0f9f981835d31e1af373b9c1851014826c9698f80373c1bb

build:
  skip: True  # [not linux]
  number: 1
  run_exports:
    - {{ pin_subpackage('libdrm', max_pin='x.x') }}
  script:
    - ./configure --prefix={{ PREFIX }}
    - make -j$(nproc) install

requirements:
  build:
    - {{ compiler('c') }}
    - pkg-config
  host:
    # build 0 of libpciaccess 0.14 didn't have the run_exports
    - libpciaccess >=0.14=*_1

test:
  commands:
    - test -f $PREFIX/include/xf86drm.h
    - test -f $PREFIX/include/xf86drmMode.h
    - test -f $PREFIX/include/libsync.h
    - test -f $PREFIX/include/libkms/libkms.h
    - test -d $PREFIX/include/libdrm
    - test -f $PREFIX/lib/libdrm.so
    - test -f $PREFIX/lib/libdrm.so.2

about:
  home: https://gitlab.freedesktop.org/mesa/drm
  license: MIT?
  license_family: MIT
  # license_file: COPYING
  summary: 'userspace library for drm'

  # The remaining entries in this section are optional, but recommended
  description: |
    This  is libdrm,  a userspace  library for  accessing the  DRM, direct
    rendering  manager, on  Linux,  BSD and  other  operating systems that
    support the  ioctl interface.  The library  provides wrapper functions
    for the  ioctls to avoid  exposing the kernel interface  directly, and
    for chipsets with drm memory manager, support for tracking relocations
    and  buffers.   libdrm  is  a  low-level library,  typically  used  by
    graphics drivers  such as the Mesa  DRI drivers, the  X drivers, libva
    and  similar projects.  New  functionality in  the kernel  DRM drivers
    typically requires  a new  libdrm, but a  new libdrm will  always work
    with an older kernel.

extra:
  recipe-maintainers:
    - hmaarrfk
