travis:
  secure:
    BINSTAR_TOKEN: nY/HXVqpV50d1G/qBP1fbcwd+GHBOkIcfESxDcPbY83FvqwlTwksREfXTbqalvXZGNiGm7sScEagBu8U+5cx7NYMTToqlwhQfPf+L7q45QhvkoAhf/AKIaMPAGv/9c7gVSQyMbCzD2eftM0i+Hrby9XFilnLmtg1jaVtwwNkYx5a8Jb3vlnojwhYhvOHSfqgvRA/gA4PQNB3NBbOGlWzJ5r+I6gWeqxlOgH6ljXdarpyfKoCY1b3FTjeUC7IMUI/9pQqYTPT8ibMWQnlBc5tXCvvdGsF+GRldmWdlSyYtf6QH7GTqftvi4x5fw20tkcKKwKD9verD+hSuK4Yh6n4Bn/t0lPEBkz+zBmk95DvinmlDN7nEL7QxRAPIi4AiXsiaLIolb4XBL1fh672g4SkBnVP82NNwxF+P2aqMbA0LyJBjFKnI27QN15B2Iquh7wNGXF5C+7TInfAjPDADL7SMtcn/AYEvmLGjLX2eJcta9Bwj94AeHnb0PuVqLZJ9DW2bsOXk+bL2/uo3EX9qC6ZPWNhcH6iTdPZu5s3qpFmqwiFcJkEvUJWsxrygafMijQLpyWPpOcuy4eFsR+KRJsJNIeGvn2obO34I1N4ssUQnr5TraodsHIxtH+u6DkvAe8vFjWvOIahJg60zXllpNDFTIk6JuLGBlYFur3k+35wOeo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
